#!/usr/bin/gawk -f

# USAGE: pipe your to.dew list to this executable.
# If the .vim files are installed, use <local leader> + f
# from within a .dew file, or run :%! path/to/dew
# to filter in place.

# Depends on GNU coreutils date.

BEGIN {
    # grab today's date YYYY-MM-DD
    "date +%F" | getline today
    close("date +%F")

    CONTEXT = "@[^ \t]+"
    DATE = "[0-9]{4}-[0-9]{2}-[0-9]{2}"

    DURATION = "[0-9]+(d|w|m|y)"
    WEEKDAY = "(sun|mon|tue|wed|thu|fri|sat)"

    DEFER = "(>" DURATION "|>" WEEKDAY ")\\>"

    RELATIVE_REPEAT = "+{2}(" DURATION "|" WEEKDAY ")"
    ANCHORED_REPEAT = "+" DURATION

    TASK_STATUS["PENDING"] =    " "
    TASK_STATUS["INBOX"] =      "?"
    TASK_STATUS["NEXT"] =       ">"
    TASK_STATUS["SCHEDULED"] =  "$"
    TASK_STATUS["DELEGATED"] =  "%"
    TASK_STATUS["SOMEDAY"] =    "&"
    TASK_STATUS["COMMENT"] =    ":"
    TASK_STATUS["DONE"] =       "~"
    TASK_STATUS["HEADER"] =     "#"

    # build reverse map
    for (s in TASK_STATUS)
        STATUS_FROM_SIGIL[TASK_STATUS[s]] = s

    PROJECT_ORDER = "HEADER NEXT PENDING DELEGATED SCHEDULED DONE"
    split(PROJECT_ORDER, PROJECT_ORDER_PARTS)
    OUTPUT_ORDER = "INBOX LIVE DORMANT SOMEDAY COMPLETED"
    split(OUTPUT_ORDER, OUTPUT_ORDER_PARTS)

    DEFAULT_TASK_STATUS = TASK_STATUS["PENDING"]

    PROCESSED = ".+~$"

    print ": -- dew task filter --"
}

## Cleanup ##

# collapse multi-line spacing
! NF && last_line_blank { next }
!NF { last_line_blank = 1 }
NF { last_line_blank = 0 }

# process projects at newline boundary
!NF { cache_project(); next }

# trim whitespace
{ gsub(/(^[ \t]+|[ \t]+$)/, "") } 

{ status = task_status() }

status == 0 {
    # add, rather than substitute with change_status()
    $0 = DEFAULT_TASK_STATUS $0
    status = task_status()
}

# skip machine comments
status == "COMMENT" { next }

# defer macro
$0 ~ DEFER {
    defer_expr = copy(DEFER, $0)
    gsub(/>/, "", defer_expr)
    if (defer_expr ~ WEEKDAY)
        new_date = dow_offset(defer_expr)
    else
        new_date = duration_offset(today, defer_expr)

    gsub(DATE, "") # kill any old date
    sub(DEFER, new_date)
    gsub(DEFER, "") # kill any duplicate defers
}

## Non-Project tasks ##

# directly cache to inbox and someday to respective outputs
status == "INBOX" { output["INBOX"][++output_n["INBOX"]] = $0; next }
status == "SOMEDAY" { output["SOMEDAY"][++output_n["SOMEDAY"]] = $0; next }

# repeat handlers

status == "DONE" && \
$0 !~ PROCESSED && \
$0 ~ RELATIVE_REPEAT {
    repeat_expr = copy(RELATIVE_REPEAT, $0)
    gsub(/+/, "", repeat_expr) #strip sigils

    if(repeat_expr ~ WEEKDAY)
        new_date = dow_offset(repeat_expr)
    if(repeat_expr ~ DURATION)
        new_date = duration_offset(today, repeat_expr)
    
    store_old_and_repeat(new_date)
}

status == "DONE" && \
$0 !~ PROCESSED && \
$0 ~ ANCHORED_REPEAT {
    repeat_expr = copy(ANCHORED_REPEAT, $0)
    gsub(/+/, "", repeat_expr) #strip sigils
    
    if ($0 ~ DATE)
        old_date = copy(DATE, task[tid])
    else
        old_date = today

    new_date = duration_offset(old_date, repeat_expr)
    store_old_and_repeat(new_date)
}

/^[%$]/ && $0 !~ DATE {
    task_lint("No follow-up date. Assign one with YYYY-MM-DD or a shortcut, e.g. '>2w'.")
}

status == "DELEGATED" {
    if ($1 == TASK_STATUS["DELEGATED"]) # i.e., '%' then a space
        task_lint("Delegated to whom? Use '%person'.")
    else
        delegated_to[$1]++
}

# activate any due dates
(status == "SCHEDULED" || status == "DELEGATED") && \
$0 ~ DATE {
    date_string = copy(DATE, $0)

    if(date_string <= today)
        change_status("NEXT")
}

# downgrade deferred next actions
status == "NEXT" && $0 ~ DATE {
    date_string = copy(DATE, $0)

    if(date_string > today)
        change_status("DELEGATED")
}

# record contexts from next tasks
status == "NEXT" && \
$0 ~ CONTEXT {
    context = copy(CONTEXT, $0)
    contexts[context]++
}

# store tasks into project
{
    project[status][++project_n[status]] = $0
}
# 'next' is reserved; referred to as "workable" in codebase
#task_status() == "NEXT" { workable[++workable_n] = $0; next }
#task_status() == "HEADER"{ header[++header_n] = $0; next }
#task_status() == "PENDING" { pending[++pending_n] = $0; next}
#task_status() == "SCHEDULED" { scheduled[++scheduled_n] = $0; next }
#task_status() == "DELEGATED" { delegated[++delegated_n] = $0; next }
#task_status() == "DONE" { done[++done_n] = $0; next }

END {
    cache_project() # guards against files not ending in \n

    # these sections aren't generated via cache_project_as(),
    # so they need a line feed to sep from later sections
    inbox_n = output_n["INBOX"] # prevent off by one from following:
    output["INBOX"][++output_n["INBOX"]] = ""
    output["SOMEDAY"][++output_n["SOMEDAY"]] = ""

    if (lints)
        print ": lints: " lints "\n: Search for ':!' to correct.\n"

    print ": inbox: " (inbox_n ? inbox_n : "empty!")

    if(isarray(contexts)) {
        print ": context counts:"
        for (i in contexts)
            print ":\t" i ": " contexts[i]
    }
    if(isarray(delegated_to)) {
        print ": delegated counts:"
        for (i in delegated_to)
            print ":\t" i ": " delegated_to[i]
    }
    print ""

    for( i = 1; i <= length(OUTPUT_ORDER_PARTS); i++) {
        sec = OUTPUT_ORDER_PARTS[i]
        
        print ": " sec
        for(j = 1; j <= output_n[sec]; j++) {
            print output[sec][j]
        }
    }
}

function cache_project() {
    if (project_n["NEXT"]) {
        cache_project_as("LIVE")
        return
    }

    if (project_n["DELEGATED"] || project_n["SCHEDULED"]) {
        cache_project_as("DORMANT")
        return
    }

    # no follow-up and not completed
    if (project_n["PENDING"] ||
    (project_n["HEADER"] && !project_n["DONE"])) {
        cache_project_as("LIVE", "Project is stalled. Assign a next action or follow-up.")
        return
    }

    # possible header and >1 done:
    if (project_n["DONE"]) {
        cache_project_as("COMPLETED")
        return
    }

    # no tasks at all: do nothing
    return
}

function cache_project_as(section, lint,    order, i, status, j) {
    # store any project lint warnings
    if (lint) {
        output[section][++output_n[section]] = ":! " lint
        lints++
    }
    
    for(i = 1; i <= length(PROJECT_ORDER_PARTS); i++) {
        status = PROJECT_ORDER_PARTS[i]
        for(j = 1; j <= project_n[status]; j++)
            output[section][++output_n[section]] = project[status][j]
    }

    output[section][++output_n[section]] = ""
    clear_project_cache()
}

function change_status(new_status) {
    sub(/./, TASK_STATUS[new_status])
    status = task_status() # refresh global status variable
}

function clear_project_cache() {
    delete project
    delete project_n
}

function duration_offset(repeat_from, repeat_expr,  cmd, result) {
    # repeat_expr is necessarily (int)(duration), e.g. "2w"
    # expand to make `date` happy
    # NB: trailing space neutralizes subsequent sub()s
    # to prevent "1d" -> "1 day" -> "1 da year"
    sub(/d$/, " day ",   repeat_expr)
    sub(/w$/, " week ",  repeat_expr)
    sub(/m$/, " month ", repeat_expr)
    sub(/y$/, " year ",  repeat_expr)

    cmd = "date -d '" repeat_from " +" repeat_expr "' +%F"
    cmd | getline result
    close(cmd)
    return result
}

function dow_offset(dow,  cmd, result) {
    cmd = "date -d 'next " dow "' +%F"
    cmd | getline result
    close(cmd)
    return result
}

function copy(pattern, string) {
    if (match(string, pattern))
        return substr(string, RSTART, RLENGTH)
    return ""
}

function store_old_and_repeat(new_date) {
    # store cancelled task
    project["DONE"][++project_n["DONE"]] = $0 "~"

    sub(/^~/, "$") # activate
    gsub(DATE, "") # delete any old dates
    $0 = $0 " " new_date
}

function task_lint(msg) {
    $0 = $0 "\n:! " msg
    lints++
}

function task_status() {
    if(substr($0,1,1) in STATUS_FROM_SIGIL)
        return STATUS_FROM_SIGIL[substr($0,1,1)]
    
    return 0 # non-matched
}