#!/usr/bin/awk -f

# USAGE: pipe your to.dew list to this executable.
# If the .vim files are installed, use <local leader> + f
# from within a .dew file, or run :%! path/to/dew
# to filter in place.

BEGIN {
    # grab today's date YYYY-MM-DD
    "date +%F" | getline today
    close("date +%F")

    date_regex = "[0-9]{4}-[0-9]{2}-[0-9]{2}"
    # load-bearing regular expression
    repeat_regex = "+?[[] *(([0-9]+ +)?(day|week|month|year)s?( +([0-9]+ +)?(day|week|month|year)s?)*|(sun|mon|tue(s)?|thu(rs)?|fri)(day)?|(wed(nesday)?)|(sat(urday)?)) *]"
}

## Cleanup
# strip leading and trailing whitespace
{ gsub(/(^[ \t]+|[ \t]+$)/, "") }

# skip stray one-character lines
/^.$/ { next }

# skip machine comments
/^:/ { next }

# collapse multi-line spacing
!NF {
    if (prev_line_is_blank) next
    prev_line_is_blank = 1
}
NF { prev_line_is_blank = 0 }

## Special sections
# directly cache to inbox and someday to respective outputs
/^\?/ { output["inbox"][++output_n["inbox"]] = $0; next }
/^&/ { output["someday"][++output_n["someday"]] = $0; next }

## Task is a bona fide project:
# headers
/^#/   { header[++header_n] = $0; next }

# repeat handler
$0 ~ repeat_regex && /^~.+[^~]$/ {
    # store cancelled task and change status
    done[++done_n] = $0 "~"
    sub(/^~/, "$")

    # extract repeat expression
    match($0, repeat_regex)
    repeat_expr = substr($0, RSTART, RLENGTH)
    
    # Repeat from last scheduled date if it's available AND
    # We're not relative repeating (e.g. +[3 days])
    if ($0 ~ date_regex && repeat_expr ~ /^[^+]/) {
        match($0, date_regex)
        repeat_from = substr($0, RSTART, RLENGTH)
    } else {
        repeat_from = today
    }

    gsub(/[\+\[\]]/, "", repeat_expr) # tidy for `date`
    gsub(date_regex, "")
    new_date = date_offset(repeat_from, repeat_expr)
    $0 = $0 " " new_date
}


/^~/ { done[++done_n] = $0; next }

/^[%$]/ && $0 !~ date_regex {
    $0 = $0 "\n:! No follow-up date assigned."
    lints++
}

/^%/ {
    if ($1 == "%") {
        $0 = $0 "\n:! Delegated to whom?"
        lints++
    }
    else
        delegated_to[$1]++
}


# activate any due dates
/^[%$]/ && $0 ~ date_regex {
    match($0, date_regex)
    date_string = substr($0, RSTART, RLENGTH)

    if(date_string <= today)
        $0 = ">" $0
}

/^\$/ { scheduled[++scheduled_n] = $0; next }
/^%/  { delegated[++delegated_n] = $0; next }

# record contexs from next tasks
/^>.*@.+/ {
    for(i = 1; i <= NF; i++) {
        if(match($i, /^@.+$/)) {
            contexts[$i]++
        }
    }
}

# 'next' is reserved; referred to as "workable" in codebase
/^>/    { workable[++workable_n] = $0; next }

# any non-matched items: indent then cache
NF {
    $0 = " " $0
    pending[++pending_n] = $0
    next
}

# line must be blank to continue:
# blanks are implicit end of project

workable_n {
    project_print("live")
    next
}

delegated_n || scheduled_n {
    project_print("dormant")
    next
}

pending_n || (header_n && !done_n) {
    project_print("live", ":! Project is stalled. Assign a next action or follow-up.")
    lints++
    next
}

# only done tasks:
{ project_print("completed") }

function project_print(section, lint) {
    # store any lints
    if (lint)
        output[section][++output_n[section]] = lint
    
    # transfer project block to its output section
    append_section(section, header, header_n)
    append_section(section, done, done_n)
    append_section(section, workable, workable_n)
    append_section(section, delegated, delegated_n)
    append_section(section, scheduled, scheduled_n)
    append_section(section, pending, pending_n)

    output[section][++output_n[section]] = ""

    clear_project_cache()
}

function append_section(section, arr, count,    i) {
    for (i = 1; i <= count; i++) {
        output[section][++output_n[section]] = arr[i]
    }
}

function clear_project_cache() {
    delete header
    delete done
    delete workable
    delete delegated
    delete scheduled
    delete pending

    header_n = done_n = workable_n = delegated_n = scheduled_n = pending_n = 0
}

END {
    if (lints)
        print ": lints: " lints "\n: Search for ':!' to correct.\n"

    print ": inbox:", output_n["inbox"]

    print ": context counts:"
    for (i in contexts)
        print ":\t" i ": " contexts[i]
    print ": delegated counts:"
    for (i in delegated_to)
        print ":\t" i ": " delegated_to[i]
    printf("\n")

    output_section[1] = "inbox"
    output_section[2] = "live"
    output_section[3] = "dormant"
    output_section[4] = "someday"
    output_section[5] = "completed"

    for( i = 1; i <= 5; i++) {
        sec = output_section[i]
        print ""
        print ": " sec
        for(j = 1; j <= output_n[sec]; j++) {
            print output[sec][j]
        }
    }
}

function date_offset(repeat_from, repeat_expr,  cmd, result) {
    cmd = "date -d '" repeat_from " +" repeat_expr "' +%F"
    cmd | getline result
    close(cmd)
    return result
}